version: 1.0.0
log_level: info
app_name: ListTheseServers
app_short_name: LTS

api:
  usingHttps: false
  port: 8080
  allowed_methods:
    - GET
    - POST
  allowed_headers:
    - Content-Type
  allowed_origins:
    - \*

database:
  host: 127.0.0.1:5432
  user: spidernet
  password: spidernet
  database: spidernet
  sslmode: disable
  
secrets:
  csrf: some-generated-256-bit-secret
  jwtsecret: some-generated-256-bit-secret
