version: 1.0.0
log_level: info
app_name: spidernet
app_short_name: SN

api:
  usingHttps: false
  port: 8081
  allowed_methods:
    - GET
    - POST
  allowed_headers:
    - Content-Type
  allowed_origins:
    - "*"

database:
  host: 127.0.0.1
  port: 52602
  user: spidernet
  password: spidernet
  database: spidernet
  sslmode: disable
  
secrets:
  csrf: some-secret-256-bit-key
  jwtsecret: another-secret-256-bit-key
  api_login: some-secret-api-login-for-development
